apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: "grafana"
  labels:
    app.kubernetes.io/name: "grafana"
spec:
  selector:
    matchLabels:
     app.kubernetes.io/name: "grafana"
  componentKinds:
    - group: v1
      kind: Service
    - group: apps
      kind: StatefulSet
  addOwnerRef: true
  descriptor:
    type: "grafana"
    keywords:
      - "monitoring"
      - "dashboard"
      - "grafana"
    links:
      - description: About
        url: "https://grafana.com/"
    version: "4.9.4"
    description: "Grafana Monitoring Dashboards"
    icons:
      - src: "https://s.w.org/style/images/about/WordPress-logotype-wmark.png"
        type: "image/png"
        size: "1000x1000"
      - src: "https://s.w.org/style/images/about/WordPress-logotype-standard.png"
        type: "image/png"
        size: "2000x680"
    maintainers:
      - name: Grafana Dev
        email: dev@grafana.com
    owners:
      - name: grafana Admin
        email: admin@grafana.com